### ISSUE TITLE
New registration todo list

### ISSUE THREAD

**Issue by addaleax** [tradity/tradity-client#8]
- [x] Autocomplete for group choice
- [x] Birthday datepicker
- [x] Error messages for existing users/email addresses
- [x] German translation of new messages
- [x] Adapt "tooltips"
- [x] Error messages are not displayed (vm.alerts.push…)
- [x] First “Let’s go” button should not work when passwords are different
- [x] Redirection when already logged in
- [ ] **Make school-based registration and invite links work** X
- [x] Questionnaire should turn in valid results
- [x] Choose language before the second page
- [x] Add gender to regular options page
- [x] Fix display errors with Chromium
- [ ] Prevent user premature access to next step without complete previous step
- [x] Adapt design for school and school class fields
- [ ] Auto close error messages when input data is valid or user can process to the next step
- [x] Make school/uni input obligatory

Feel free to add more items.

cc @nhaesler @BonsaiOfHappiness

**Comment by nhaesler** [comment]
- [] Error messages are not displayed (vm.alerts.push…)

**Comment by addaleax** [comment]
@hieutran Nico and I are going to sleep now, maybe you could take a look at some of the above issues? We merged our changes to the `stable` branch, meaning that our production users now actually use the new registration form. It would be great if you could try and fix some of the remaining problems so that they don’t run into them? :)

**Comment by hieutran** [comment]
@addaleax @nhaesler Roger that! Have a nice dream :)

**Comment by addaleax** [comment]
Merged your commits into master… maybe someone else can check at dev.tradity.de if everything works, but they look good to me

**Comment by hieutran** [comment]
Can you explain "Adapt 'tooltips'" in this todo list?

**Comment by addaleax** [comment]
@BonsaiOfHappiness ?

**Comment by hieutran** [comment]
And also 'Add gender to regular options page'?

**Comment by addaleax** [comment]
I don’t know if you have seen it, but basically you can edit all your personal data at `/options`; Since the gender chooser is a new feature, it’s not yet included in the options page, but at some point it should be.

**Comment by hieutran** [comment]
Ah, ok, I got it :)

**Comment by BonsaiOfHappiness** [comment]
Adapt "tooltips" is a todo for me :) I mean those "enter your..." strings

**Comment by BonsaiOfHappiness** [comment]
@hieutran Could you please make it so the two fields school and school class are of the same design as the rest and have popovers as well please? :)

**Comment by hieutran** [comment]
@BonsaiOfHappiness @addaleax  Can I apply registration input style to all input in general option page? The "group chooser" input has been applied this style as checklist above, thus, their style is slightly difference with others in general option page.

**Comment by addaleax** [comment]
I don’t see any problem with that and I guess it’s a good idea to have a consistent style, but then again, I’m terrible at design stuff ;)

**Comment by BonsaiOfHappiness** [comment]
Yes, please :)

**Comment by BonsaiOfHappiness** [comment]
@nhaesler Any advances regarding school-based registrations?

**Comment by hieutran** [comment]
@BonsaiOfHappiness I applied this style to all input in general option page. I don't clearly understand your "also".

**Comment by BonsaiOfHappiness** [comment]
@hieutran Right now the school/uni input field doesn't need to be filled to finish the registration. We'd like it to be like name, email etc. - so you have to choose a group (school/uni) in order to finish the registration.

Not the school class/semester field though.

**Comment by hieutran** [comment]
@BonsaiOfHappiness I got it!
@addaleax I need support from backend for comment from Ba Khai.

**Comment by addaleax** [comment]
That depends on what Ba Khai wants here – should users be able to leave a group later or is a new user without a group always considered an invalid state? Right now, the system is build in such a way that users can leave the group by various means, and tbh I think that just makes sense.

So what I’d prefer is that providing a group is only obligatory at the registration, which can and should be checked on the client-side (since nothing bad is happening when they work around that by modifying the code).

Or does @BonsaiOfHappiness mean that one has to pick either a group or the “no group” field? I feel like there is a little more room for clarification here :)

**Comment by hieutran** [comment]
@addaleax I also need your backend support for general option page: 
- implement backend API for gender save and load, 
- please check my birthday datepicker implementation: it's only show epoch time when I refresh the option page.

**Comment by addaleax** [comment]
There should be no backend support necessary other than what is already present, I think; Can I merge your commits? If that’s all that left, I will take a look

**Comment by hieutran** [comment]
Yes. please :)

**Comment by addaleax** [comment]
Both should work now, although the picked gender is not displayed in the options page (?)

**Comment by addaleax** [comment]
Oh and btw, why do you insert spaces at the end of HTML attribute values? I find it somewhat confusing to read `ng-value="{{$index}} "`, because I’d not be sure whether the space at the end is actually included in the value or not…

**Comment by hieutran** [comment]
I didn't do that. Which file has this problem?

**Comment by hieutran** [comment]
Ahh, I found it. It represent in registration step 2, few days ago, I got the code formatting config error on my IDE.

**Comment by addaleax** [comment]
Ah ok – just so I know it’s not intentional or anything :)

**Comment by hieutran** [comment]
@BonsaiOfHappiness Can you explain the "Make school/uni input obligatory" task follow the @addaleax 's comment above?

**Comment by BonsaiOfHappiness** [comment]
@hieutran Yes, sorry - overlooked the notifications.

We'd like the users to have to choose a group during the registration (either an existing group, creating a new group or choosing "no group" like addaleax said). 

User should be allowed to leave the group once they are in the game (we don't need to remind them or anything though). I hope this clarifies things?

**Comment by nhaesler** [comment]
old client version
